name: Build and Release

# 触发规则
on:
  push:
    branches:
      - 'test' # 测试

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug
        run: date >> README.md

      - name: Create release or pre-release
        id: create_release
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # 如果是标签推送，创建正式版本
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "Creating release for tag $TAG_NAME"
            PRE_RELEASE=false
          elif [[ $GITHUB_REF == refs/heads/test ]]; then
            # 如果是 test 分支推送，创建预发布版本
            COMMIT_ID=$(git rev-parse --short HEAD)
            echo "Creating pre-release for commit $COMMIT_ID"
            TAG_NAME="pre-release-${COMMIT_ID}"
            PRE_RELEASE=true
          fi

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "PRE_RELEASE=$PRE_RELEASE" >> $GITHUB_ENV


      - name: Upload release assets (zip files)
        uses: softprops/action-gh-release@v2
        with:
          files: README.md
          tag_name: ${{env.TAG_NAME}}
          prerelease: ${{env.PRE_RELEASE}}
